import type { ColorTokens } from './types.js';

const neutralLight: ColorTokens = {
  background: '#ffffff',
  foreground: '#0a0a0a',
  card: '#ffffff',
  'card-foreground': '#0a0a0a',
  popover: '#ffffff',
  'popover-foreground': '#0a0a0a',
  primary: '#171717',
  'primary-foreground': '#fafafa',
  secondary: '#f5f5f5',
  'secondary-foreground': '#171717',
  muted: '#f5f5f5',
  'muted-foreground': '#737373',
  accent: '#f5f5f5',
  'accent-foreground': '#171717',
  destructive: '#ef4444',
  'destructive-foreground': '#fafafa',
  border: '#e5e5e5',
  input: '#e5e5e5',
  ring: '#a3a3a3',
  'chart-1': '#e76e50',
  'chart-2': '#2a9d90',
  'chart-3': '#274754',
  'chart-4': '#e8c468',
  'chart-5': '#f4a462',
};

const neutralDark: ColorTokens = {
  background: '#0a0a0a',
  foreground: '#fafafa',
  card: '#0a0a0a',
  'card-foreground': '#fafafa',
  popover: '#0a0a0a',
  'popover-foreground': '#fafafa',
  primary: '#fafafa',
  'primary-foreground': '#171717',
  secondary: '#262626',
  'secondary-foreground': '#fafafa',
  muted: '#262626',
  'muted-foreground': '#a3a3a3',
  accent: '#262626',
  'accent-foreground': '#fafafa',
  destructive: '#7f1d1d',
  'destructive-foreground': '#fafafa',
  border: '#262626',
  input: '#262626',
  ring: '#525252',
  'chart-1': '#3b82f6',
  'chart-2': '#10b981',
  'chart-3': '#f59e0b',
  'chart-4': '#a855f7',
  'chart-5': '#ec4899',
};

const minimalLight: ColorTokens = {
  ...neutralLight,
  primary: '#404040',
  'primary-foreground': '#fafafa',
  muted: '#f0f0f0',
  'muted-foreground': '#6b6b6b',
  accent: '#ebebeb',
  ring: '#8c8c8c',
};

const minimalDark: ColorTokens = {
  ...neutralDark,
  primary: '#d4d4d4',
  'primary-foreground': '#171717',
  muted: '#1f1f1f',
  'muted-foreground': '#8c8c8c',
  accent: '#2a2a2a',
  ring: '#6b6b6b',
};

const saasLight: ColorTokens = {
  ...neutralLight,
  primary: '#2563eb',
  'primary-foreground': '#ffffff',
  secondary: '#eff6ff',
  'secondary-foreground': '#1e3a8a',
  accent: '#dbeafe',
  'accent-foreground': '#1e40af',
  ring: '#3b82f6',
  'chart-1': '#2563eb',
  'chart-2': '#0ea5e9',
  'chart-3': '#6366f1',
};

const saasDark: ColorTokens = {
  ...neutralDark,
  primary: '#3b82f6',
  'primary-foreground': '#ffffff',
  secondary: '#1e3a5f',
  'secondary-foreground': '#dbeafe',
  accent: '#1e40af',
  'accent-foreground': '#dbeafe',
  ring: '#60a5fa',
  'chart-1': '#60a5fa',
  'chart-2': '#38bdf8',
  'chart-3': '#818cf8',
};

const warmLight: ColorTokens = {
  ...neutralLight,
  background: '#fffbf7',
  foreground: '#292524',
  card: '#fffbf7',
  'card-foreground': '#292524',
  popover: '#fffbf7',
  'popover-foreground': '#292524',
  primary: '#c2410c',
  'primary-foreground': '#fff7ed',
  secondary: '#ffedd5',
  'secondary-foreground': '#7c2d12',
  muted: '#fef3c7',
  'muted-foreground': '#78716c',
  accent: '#fed7aa',
  'accent-foreground': '#7c2d12',
  border: '#e7e5e4',
  input: '#e7e5e4',
  ring: '#ea580c',
  'chart-1': '#ea580c',
  'chart-2': '#d97706',
  'chart-3': '#b45309',
};

const warmDark: ColorTokens = {
  ...neutralDark,
  background: '#1c1917',
  foreground: '#fafaf9',
  card: '#1c1917',
  'card-foreground': '#fafaf9',
  popover: '#1c1917',
  'popover-foreground': '#fafaf9',
  primary: '#fb923c',
  'primary-foreground': '#431407',
  secondary: '#44403c',
  'secondary-foreground': '#fed7aa',
  muted: '#292524',
  'muted-foreground': '#a8a29e',
  accent: '#44403c',
  'accent-foreground': '#fed7aa',
  border: '#44403c',
  input: '#44403c',
  ring: '#fb923c',
  'chart-1': '#fb923c',
  'chart-2': '#fbbf24',
  'chart-3': '#f97316',
};

const boldLight: ColorTokens = {
  ...neutralLight,
  background: '#ffffff',
  foreground: '#09090b',
  primary: '#7c3aed',
  'primary-foreground': '#ffffff',
  secondary: '#f4f4f5',
  'secondary-foreground': '#18181b',
  muted: '#f4f4f5',
  'muted-foreground': '#52525b',
  accent: '#ede9fe',
  'accent-foreground': '#5b21b6',
  destructive: '#dc2626',
  border: '#d4d4d8',
  input: '#d4d4d8',
  ring: '#7c3aed',
  'chart-1': '#7c3aed',
  'chart-2': '#db2777',
  'chart-3': '#0891b2',
};

const boldDark: ColorTokens = {
  ...neutralDark,
  background: '#09090b',
  foreground: '#fafafa',
  card: '#09090b',
  'card-foreground': '#fafafa',
  primary: '#a78bfa',
  'primary-foreground': '#1e1b4b',
  secondary: '#27272a',
  'secondary-foreground': '#fafafa',
  muted: '#27272a',
  'muted-foreground': '#a1a1aa',
  accent: '#3f3f46',
  'accent-foreground': '#ede9fe',
  border: '#3f3f46',
  input: '#3f3f46',
  ring: '#a78bfa',
  'chart-1': '#a78bfa',
  'chart-2': '#f472b6',
  'chart-3': '#22d3ee',
};

export const presets = {
  neutral: {
    id: 'neutral' as const,
    name: 'Neutral',
    description: 'Balanced default look close to shadcn out of the box.',
    defaultBrandColor: neutralLight.primary,
    defaultFont: 'inter',
    defaultRadius: 'default' as const,
    light: neutralLight,
    dark: neutralDark,
  },
  minimal: {
    id: 'minimal' as const,
    name: 'Minimal',
    description: 'Muted neutrals with a tighter, understated feel.',
    defaultBrandColor: minimalLight.primary,
    defaultFont: 'inter',
    defaultRadius: 'sharp' as const,
    light: minimalLight,
    dark: minimalDark,
  },
  saas: {
    id: 'saas' as const,
    name: 'SaaS',
    description: 'Clean product UI with a confident blue accent.',
    defaultBrandColor: saasLight.primary,
    defaultFont: 'geist',
    defaultRadius: 'default' as const,
    light: saasLight,
    dark: saasDark,
  },
  warm: {
    id: 'warm' as const,
    name: 'Warm',
    description: 'Warm neutrals and soft corners for a friendly tone.',
    defaultBrandColor: warmLight.primary,
    defaultFont: 'nunito',
    defaultRadius: 'soft' as const,
    light: warmLight,
    dark: warmDark,
  },
  bold: {
    id: 'bold' as const,
    name: 'Bold',
    description: 'High-contrast accent with sharp corners for impact.',
    defaultBrandColor: boldLight.primary,
    defaultFont: 'dm-sans',
    defaultRadius: 'sharp' as const,
    light: boldLight,
    dark: boldDark,
  },
};
